// <auto-generated />
using System;
using LoanApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanApplication.Migrations
{
    [DbContext(typeof(LoanContext))]
    [Migration("20240703202801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("LoanApplication.Model.AggregatedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCollateralValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalExpectedLoss")
                        .HasColumnType("REAL");

                    b.Property<decimal>("TotalOutstandingLoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalScenarioCollateralValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AggregatedResults");
                });

            modelBuilder.Entity("LoanApplication.Model.CalculationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeTaken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalculationRuns");
                });

            modelBuilder.Entity("LoanApplication.Model.PercentageChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Change")
                        .HasColumnType("REAL");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalculationRunId");

                    b.ToTable("PercentageChange");
                });

            modelBuilder.Entity("LoanApplication.Model.PercentageChange", b =>
                {
                    b.HasOne("LoanApplication.Model.CalculationRun", "CalculationRun")
                        .WithMany("PercentageChanges")
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationRun");
                });

            modelBuilder.Entity("LoanApplication.Model.CalculationRun", b =>
                {
                    b.Navigation("PercentageChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
